"""empty message

Revision ID: 46a9415d82c0
Revises: 
Create Date: 2022-06-29 19:52:17.652275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a9415d82c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variante', sa.Column('activo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variante', 'activo')
    # ### end Alembic commands ###
