"""empty message

Revision ID: 9ac581574852
Revises: 46a9415d82c0
Create Date: 2022-07-11 21:02:32.691499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac581574852'
down_revision = '46a9415d82c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portada',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('direccionPortada', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portada')
    # ### end Alembic commands ###
